name: stocksync_flutter
description: StockSync Hub - Kho Xac Linh Kien Mobile Scanner & Auto-Update
version: 1.2.9+129
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.3
  web_socket_channel: ^2.4.1
  http: ^1.2.0
  dio: ^5.4.1
  package_info_plus: ^8.0.0
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/inventory_store.json
